# Generated by Django 5.1.4 on 2025-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artist_image",
            field=models.ImageField(blank=True, null=True, upload_to="artists/pfp/"),
        ),
    ]
