# Generated by Django 5.1.4 on 2025-02-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_artist_artist_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="digitalfiles",
            options={"verbose_name_plural": "Digital Files"},
        ),
    ]
